name: Geo fix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm i
      - name: Fix geo file
        run: npm run geofix
      - name: Commit file
        run: |
          git config --global user.email "artegoser@gmail.com"
          git config --global user.name "artegoser"
          git commit -m "Publish fixed geo" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
